server:
  port: 8763

spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://192.168.1.118:9411
    sender:
      type: web
    service:
      name: consumer
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.118:8848
#暴露的健康检查服务端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.openfeign: debug
