#不使用配置中心的配置，使用配置中心，就将这些配置除端口外，添加到nacos配置中心里面
server:
  port: 8761

spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://192.168.1.118:9411
    sender:
      type: web
    service:
      name: provider
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.118:8848
logging:
  level:
    org.springframework.cloud.openfeign: debug
